name: Tester et déployer

on:
  push:
    branches: [ "main" ] # remplacer par main 
    
  pull_request:
    branches: 
      -"prod" 

jobs:
  mon-premier-job: # par exemple run test 
    runs-on: ubuntu-latest
    steps:
      - name: afficher une variable d environnement
        run: echo $NAME
        env: 
          NAME : marco
          
      - name: lister fichiers 
        run: ls -la # on observe qu'il n'y a aucun fichier de notre répertoire dnas le répertoire courant ! 
        
      - name: cloner le répo
        uses: actions/checkout@v4 # cela permet de cloner son répertoire et donc d'importer son code
        
      - name: lister fichiers 
        run: ls -la # on reliste et on observe que les fichiers sont bien présents à cette étape
        
      - name: Utiliser une variable au niveau du répo
        run: echo ${{vars.NAME}} # Il est possible de placer des variables au niveau de répertoire github et de les référencer dnas un workflow 
        
      - name: Utiliser un secret # Idem pour des secrets
        run: echo $MY_PASSWORD > example.txt 
        env: 
          MY_PASSWORD: ${{secrets.PASSWORD}}
          
      - name: Afficher contenu du fichier # Toute information concernant un secret ne peut pas être "affichée" 
        run: cat example.txt
        
  test: # second-job
    runs-on: ubuntu-latest
    needs: mon-premier-job # cette étape de test ne peut pas se lancer avant que mon-premier-job soit fini et réussi ! 
    steps:
      - name: lister fichiers # les fichiers présents auparavant sont-ils disponibles ? 
        run: ls -la
        
      - name: cloner le répo # on reclone 
        uses: actions/checkout@v4
        
      - name: installer python  # installation de python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name:  montrer la version de python installée # on peut vérifier ici l'installation de celui-ci 
        run: python --version

      - name: installer les dépendances
        run: |
          pip install -r requirements.txt
          pip install pytest
        
      - name: Lancer les tests
        run: python -m pytest tests/
        
        
